import { MetadataRoute } from "next";

const IMPORTANT = [
  "/all-tools",
  "/utm-builder",
  "/ai-chatbot",
  "/ai-resume-builder",
  "/speech-to-text",
  "/text-to-speech",
  "/whatsapp-link-generator",
  "/youtube-banner-maker",
];

const toolHrefs = [
  "/single",
  "/utm-builder",
  "/ai-chatbot",
  "/ai-resume-builder",
  "/ai-email-writer",
  "/ai-code-generator",
  "/ai-image-generator",
  "/reverse-video",
  "/speech-to-text",
  "/text-to-speech",
  "/voice-changer",
  "/temp-upload",
  "/whatsapp-link-generator",
  "/all-units-converter",
  "/fake-data",
  "/site-backup-cloner",
  "/username-checker",
  "/domain-whois",
  "/temp-mail",
  "/gmail-alias",
  "/link-safety-checker",
  "/background-remove",
  "/telegram-file-host",
  "/image-to-link",
  "/dns-lookup",
  "/password-breach-checker",
  "/website-trust-checker",
  "/github-user",
  "/coding-resources",
  "/free-games",
  "/translate",
  "/image-gallery",
  "/holidays",
  "/pokemon",
  "/facts",
  "/pets",
  "/country",
  "/crypto-prices",
  "/quran-ayah",
  "/namaz-times",
  "/weather",
  "/speed-test",
  "/currency-converter",
  "/ip-finder",
  "/keyboard-test",
  "/image-size-increaser",
  "/wps-sheets",
  "/bio-maker",
  "/bmi-calculator",
  "/lucky-draw",
  "/tax-calculator",
  "/html-to-url",
  "/sim-data",
  "/temp-room",
  "/hide-message-photo",
  "/direct-file-share",
  "/wifi-qr-decoder",
  "/bulk",
  "/blur-face-plate",
  "/image-to-webp",
  "/images-to-gif",
  "/custom-watermark",
  "/image-border-frame",
  "/nickname-generator",
  "/lorem-ipsum-generator",
  "/hash-generator",
  "/uuid-generator",
  "/json-formatter",
  "/regex-tester",
  "/photo-enhance-fix",
  "/passport-photo-maker",
  "/rename-file",
  "/csv-to-json",
  "/json-to-csv",
  "/logo-maker",
  "/pdf-unlock",
  "/pdf-password-protect",
  "/text-to-pdf",
  "/pdf-rotator",
  "/word-to-pdf",
  "/pdf-to-image",
  "/pdf-splitter",
  "/pdf-compressor",
  "/duplicate-finder",
  "/duplicate-line-remover",
  "/whatsapp-dp-maker",
  "/pdf-merger",
  "/image-to-file",
  "/file-compressor",
  "/youtube-thumbnail-maker",
  "/password-generator",
  "/youtube-banner-maker",
  "/collage-maker",
  "/favicon-generator",
  "/metadata-remover",
  "/word-counter",
  "/color-picker",
  "/rgb-picker",
  "/markdown-preview",
  "/image-converter",
  "/image-resizer",
  "/image-compressor",
  "/image-to-pdf",
  "/photo-editor",
  "/vocal-separator",
  "/video-to-audio",
  "/video-to-gif",
  "/audio-joiner",
  "/audio-booster",
  "/letter-art",
  "/dot-art",
  "/repeater",
  "/hex-converter",
  "/code-converter",
  "/dictionary",
  "/png-finder",
  "/icon-studio",
  "/username-forge",
  "/hashtag-engine",
  "/html-site-rescue",
  "/mouse-cursor-maker",
  "/image-size-converter",
];

const blogHrefs = [
  "/blog",
  "/blog/remove-background-free",
  "/blog/merge-pdf-online",
  "/blog/compress-pdf-online",
  "/blog/image-to-pdf",
  "/blog/ai-resume-free",
  "/blog/ai-email-writer-guide",
];

const LASTMOD = new Date("2026-09-20");

function priorityFor(route: string): number {
  if (route === "/") return 1;
  if (IMPORTANT.includes(route)) return 0.9;
  if (route.startsWith("/blog")) return 0.7;
  return 0.6;
}

export default function sitemap(): MetadataRoute.Sitemap {
  const allRoutes = ["/all-tools", ...toolHrefs, ...blogHrefs];
  const uniqueRoutes = [...new Set(allRoutes)];

  const routes = uniqueRoutes.map((route) => ({
    url: `https://mykittool.online${route}`,
    lastModified: LASTMOD,
    changeFrequency: "weekly" as const,
    priority: priorityFor(route),
  }));

  return [
    {
      url: "https://mykittool.online",
      lastModified: LASTMOD,
      changeFrequency: "weekly" as const,
      priority: 1,
    },
    ...routes,
  ];
}
